# Generated by Django 4.2.16 on 2025-03-27 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="contract_file",
        ),
    ]
