# Generated by Django 4.2.16 on 2025-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_rename_created_at_contract_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="contract/"),
        ),
    ]
