# Generated by Django 4.2.16 on 2025-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0004_contract_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="payer_name",
            field=models.CharField(max_length=50),
        ),
    ]
