# Generated by Django 4.2.16 on 2025-04-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0005_alter_contract_payer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="effective_date",
            field=models.DateTimeField(default="TBA"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="contracts/"),
        ),
    ]
