# Generated by Django 4.2.16 on 2025-04-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0006_alter_contract_effective_date_alter_contract_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="effective_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
