# Generated by Django 4.2.16 on 2025-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0008_alter_contract_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="payer_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="contract",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
