# Generated by Django 4.2.16 on 2025-04-07 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0009_alter_contract_payer_name_alter_contract_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="effective_date",
        ),
    ]
